version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project/:/usr/project/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://aag_admin:secret_777@db/aag_fastapi_dev
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=aag_admin
      - POSTGRES_PASSWORD=secret_777
      - POSTGRES_DB=aag_fastapi_dev

volumes:
  postgres_data: