version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project/:/usr/project/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://test_user:secret_test@db/test_db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=secret_test
      - POSTGRES_DB=test_db
    ports:
      - "15432:5432"

volumes:
  postgres_data: